version: '3.8'

services:
  # Django Backend
  backend:
    build: ./gptinder_back
    container_name: gptinder-backend
    restart: always
    volumes:
      - ./gptinder_back:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    env_file:
      - ./gptinder_back/.env
    ports:
      - "8000:8000"
    networks:
      - gptinder-network

  # React Frontend
  frontend:
    build: ./gptinder_front
    container_name: gptinder-frontend
    restart: always
    volumes:
      - ./gptinder_front:/app
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gptinder-network

networks:
  gptinder-network:
    driver: bridge

volumes:
  backend_media:
  backend_static: 