FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install

# Копирование кода приложения
COPY . .

# Запуск в режиме разработки
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 