# Generated by Django 5.2 on 2025-04-24 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Migrate data from the many-to-many 'participants' relationship to the new 'user1' and 'user2' fields.
    We assume that each chat has exactly 2 participants.
    """
    UserChat = apps.get_model('recommendations', 'UserChat')
    
    # For all existing chats
    for chat in UserChat.objects.all():
        # Get the participants
        participants = list(chat.participants.all())
        
        # Skip chats with less than 2 participants
        if len(participants) < 2:
            continue
        
        # Set user1 and user2
        chat.user1 = participants[0]
        chat.user2 = participants[1]
        chat.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0003_userrecommendation_explanation'),
    ]

    operations = [
        # First add new fields without constraints
        migrations.AddField(
            model_name='userchat',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchat',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        
        # Run data migration to fill user1 and user2 fields
        migrations.RunPython(forwards_func),
        
        # Make fields non-nullable now that they have data
        migrations.AlterField(
            model_name='userchat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together={('user1', 'user2')},
        ),
        
        # Remove participants relationship
        migrations.RemoveField(
            model_name='userchat',
            name='participants',
        ),
    ]
