# Generated by Django 5.1.7 on 2025-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Embedding Vector'),
        ),
        migrations.AddField(
            model_name='user',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Embedding Updated At'),
        ),
    ]
