# Generated by Django 5.2 on 2025-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_embedding_user_embedding_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tags',
            field=models.JSONField(blank=True, help_text='Tags and facts about the user extracted from AI conversations', null=True, verbose_name='User Knowledge Tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tags_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='User Tags Updated At'),
        ),
    ]
