# Generated by Django 5.2 on 2025-04-24 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250424_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Timestamp of user's last activity", verbose_name='Last Activity'),
        ),
    ]
